apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: "${CLUSTER_NAME}"
    fluxChart: enabled
  name: "${CLUSTER_NAME}"
  namespace: "${NAMESPACE}"
spec:
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    kind: OCIManagedCluster
    name: "${CLUSTER_NAME}"
    namespace: "${NAMESPACE}"
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    kind: OCIManagedControlPlane
    name: "${CLUSTER_NAME}"
    namespace: "${NAMESPACE}"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: OCIManagedCluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: "${CLUSTER_NAME}"
  name: "${CLUSTER_NAME}"
spec:
  compartmentId: "${OCI_COMPARTMENT_ID}"
---
kind: OCIManagedControlPlane
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
metadata:
  name: "${CLUSTER_NAME}"
  namespace: "${NAMESPACE}"
spec:
  version: "${KUBERNETES_VERSION}"
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: ${CLUSTER_NAME}-mp-0
  namespace: default
  annotations:
    "cluster.x-k8s.io/replicas-managed-by": ""
spec:
  clusterName: ${CLUSTER_NAME}
  replicas: ${NODE_MACHINE_COUNT}
  template:
    spec:
      clusterName: ${CLUSTER_NAME}
      bootstrap:
        dataSecretName: ""
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: OCIManagedMachinePool
        name: ${CLUSTER_NAME}-mp-0
      version: ${KUBERNETES_VERSION}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: OCIManagedMachinePool
metadata:
  name: ${CLUSTER_NAME}-mp-0
  namespace: default
spec:
  version: "${KUBERNETES_VERSION}"
  nodeShape: "${OCI_MANAGED_NODE_SHAPE=VM.Standard.A1.Flex}"
  sshPublicKey: "${OCI_SSH_KEY}"
  nodeSourceViaImage:
    imageId: ${OCI_MANAGED_NODE_IMAGE_ID:=""}
    bootVolumeSizeInGBs: ${OCI_MANAGED_NODE_BOOT_VOLUME_SIZE=50}
  nodeShapeConfig:
    ocpus: "${OCI_MANAGED_NODE_MACHINE_TYPE_OCPUS=1}"
    memoryInGBs: "${OCI_MANAGED_NODE_MACHINE_TYPE_MEMORY=8}"
---
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: fluxv2
spec:
  options:
    atomic: true
    timeout: 5m
    install:
      createNamespace: true
  clusterSelector:
    matchLabels:
      fluxChart: enabled
  repoURL: https://fluxcd-community.github.io/helm-charts
  chartName: flux2
  releaseName: gitops
  version: 2.9.0
  valuesTemplate: |
    multitenancy:
      enabled: true
